name: CI Local Jenkins Trigger

on:
  push:
    branches:
      - develop

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins job
        run: |
          CRUMB=$(curl -s -u admin:1100a8915863ae7507d64794f915ffb434 \
            'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')

          curl -X POST \
            -u admin:1100a8915863ae7507d64794f915ffb434 \
            -H "$CRUMB" \
            "http://localhost:8080/job/release-execution-platform/build?token=123"

